// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('system test2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('system test2', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 656, height: 680 })
    {
      const element = await driver.findElement(By.css(".css-i4bv87-MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-i4bv87-MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".css-78trlr-MuiButtonBase-root-MuiIconButton-root path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-78trlr-MuiButtonBase-root-MuiIconButton-root path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(3) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(3) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id(":r1:")).click()
    await driver.findElement(By.id(":r1:")).sendKeys("admin")
    await driver.findElement(By.id(":r3:")).click()
    await driver.findElement(By.id(":r3:")).sendKeys("admin")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(25) .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-textError"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-textError")).click()
    await driver.findElement(By.css(".MuiTypography-gutterBottom")).click()
    assert(await driver.findElement(By.css(".MuiTypography-gutterBottom")).getText() == "All Users")
    await driver.findElement(By.css(".MuiTypography-gutterBottom")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(3) > .MuiButtonBase-root")).click()
    await driver.findElement(By.id(":r7:")).click()
    await driver.findElement(By.id(":r7:")).sendKeys("abcdf")
    await driver.findElement(By.id(":r9:")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id(":r9:")).sendKeys("acbgd")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiTableRow-root:nth-child(7) .MuiButtonBase-root:nth-child(1) > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(7) .MuiButtonBase-root:nth-child(1) > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiButton-fullWidth")).click()
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(7) .MuiButtonBase-root:nth-child(2) > .MuiSvgIcon-root")).click()
    await driver.findElement(By.css(".MuiButton-textSecondary")).click()
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(4) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(4) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id(":rj:")).click()
    await driver.findElement(By.id(":rj:")).sendKeys("abcdefgh")
    await driver.findElement(By.id(":rl:")).click()
    await driver.findElement(By.id(":rl:")).sendKeys("aaaaaaaaaaaaaaaa")
    {
      const element = await driver.findElement(By.id(":rn:"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiBackdrop-root"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".Mui-focusVisible")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id(":rj:")).click()
    await driver.findElement(By.id(":rj:")).sendKeys("abcdefghww")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.id(":rl:")).click()
    await driver.findElement(By.id(":rl:")).click()
    {
      const element = await driver.findElement(By.id(":rl:"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id(":rl:")).sendKeys("weerdd")
    {
      const element = await driver.findElement(By.id(":rn:"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiBackdrop-root"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id(":rh:")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id(":rh:")).sendKeys("eeeeeeeeeeee")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id(":rr:")).click()
    await driver.findElement(By.id(":rr:")).sendKeys("a voya")
    await driver.findElement(By.css(".MuiTableCell-root .css-1i36c1g-MuiSvgIcon-root > path")).click()
    await driver.findElement(By.id(":r15:")).click()
    await driver.findElement(By.id(":r19:")).click()
    {
      const element = await driver.findElement(By.id(":r1b:"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".Mui-selected"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(4)")).click()
    await driver.findElement(By.css(".css-kqzn6m-MuiButtonBase-root-MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiInputAdornment-root > .MuiButtonBase-root > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiInputAdornment-root > .MuiButtonBase-root > .MuiSvgIcon-root")).click()
    await driver.findElement(By.id(":rt:")).click()
    {
      const element = await driver.findElement(By.css(".css-11d21uu-MuiSvgIcon-root > path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id(":rt:")).sendKeys("mr ab")
    await driver.findElement(By.css(".css-11d21uu-MuiSvgIcon-root > path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiButton-textPrimary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-textPrimary")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiButton-textSecondary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-textSecondary")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id(":rv:")).click()
    {
      const element = await driver.findElement(By.css(".MuiInputAdornment-root > .MuiButtonBase-root > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiInputAdornment-root > .MuiButtonBase-root > .MuiSvgIcon-root")).click()
    await driver.findElement(By.id(":rv:")).click()
    await driver.findElement(By.id(":rv:")).sendKeys("childre")
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(4) .MuiButtonBase-root:nth-child(2) path")).click()
    await driver.findElement(By.css(".MuiButton-textPrimary")).click()
    {
      const element = await driver.findElement(By.css(".MuiInputAdornment-root > .MuiButtonBase-root > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiInputAdornment-root > .MuiButtonBase-root > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(5) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(5) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(1) .MuiButtonBase-root")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(6) > .MuiButtonBase-root")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(7) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.css(".css-1wrhr06-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.close()
  })
})
