// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('system test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('system test1', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1296, height: 696 })
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .MuiButtonBase-root")).click()
    await driver.findElement(By.id(":r1:")).click()
    await driver.findElement(By.id(":r1:")).sendKeys("sampledata")
    await driver.findElement(By.id(":r3:")).click()
    await driver.findElement(By.id(":r3:")).sendKeys("sampledata@gmail.com")
    await driver.findElement(By.id(":r5:")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id(":r5:")).sendKeys("sampledata")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(5) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.css(".css-1wrhr06-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("#\\3Ar7\\3A")).click()
    await driver.findElement(By.id(":r7:")).sendKeys("sampledata")
    await driver.findElement(By.id(":r9:")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id(":r9:")).sendKeys("sampledata")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(3) > .MuiButtonBase-root")).click()
    await driver.findElement(By.id(":rb:")).click()
    await driver.findElement(By.id(":rb:")).sendKeys("the re")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.css(".css-i4bv87-MuiSvgIcon-root:nth-child(1) > path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-i4bv87-MuiSvgIcon-root:nth-child(1) > path")).click()
    await driver.findElement(By.id(":rd:")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id(":rd:")).sendKeys("step")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id(":rf:")).click()
    {
      const element = await driver.findElement(By.css(".css-i4bv87-MuiSvgIcon-root:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-i4bv87-MuiSvgIcon-root:nth-child(1)")).click()
    await driver.findElement(By.id(":rf:")).click()
    await driver.findElement(By.id(":rf:")).sendKeys("childre")
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root .MuiButtonBase-root")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .MuiPaper-root .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.css(".css-i4bv87-MuiSvgIcon-root:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-i4bv87-MuiSvgIcon-root:nth-child(1)")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(4) > .MuiButtonBase-root")).click()
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.id(":rh:")).click()
    await driver.findElement(By.id(":rj:")).click()
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.css(".MuiButton-textSecondary")).click()
    await driver.findElement(By.css(".MuiButton-outlined")).click()
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root .MuiButtonBase-root:nth-child(1)")).click()
    await driver.findElement(By.css(".MuiButton-containedPrimary")).click()
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root .MuiButtonBase-root:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root .MuiButtonBase-root:nth-child(1)")).click()
    await driver.findElement(By.css(".MuiButton-containedSecondary")).click()
    await driver.findElement(By.css(".css-dqr9h-MuiRating-label:nth-child(1)")).click()
    await driver.findElement(By.css(".css-dqr9h-MuiRating-label:nth-child(3)")).click()
    await driver.findElement(By.css(".css-dqr9h-MuiRating-label:nth-child(5)")).click()
    await driver.findElement(By.css(".css-dqr9h-MuiRating-label:nth-child(7)")).click()
    await driver.findElement(By.css(".css-dqr9h-MuiRating-label:nth-child(7)")).click()
    await driver.findElement(By.css(".css-dqr9h-MuiRating-label:nth-child(9)")).click()
    await driver.findElement(By.id(":rd:")).click()
    await driver.findElement(By.css("#\\3Ard\\3A")).sendKeys("nice")
    await driver.findElement(By.css(".css-zcbmsk-MuiButtonBase-root-MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-containedSecondary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-containedSecondary")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".css-dqr9h-MuiRating-label:nth-child(9)")).click()
    await driver.findElement(By.id(":rr:")).click()
    {
      const element = await driver.findElement(By.css(".css-bh137t-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id(":rr:")).sendKeys("nice book")
    await driver.findElement(By.css(".css-bh137t-MuiButtonBase-root-MuiButton-root")).click()
    await driver.findElement(By.css(".MuiButton-containedPrimary")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) > .MuiPaper-root .MuiButtonBase-root:nth-child(2)")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) .MuiButtonBase-root:nth-child(2)")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(5) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.css(".css-1wrhr06-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.close()
  })
})
